before_install:
 - chmod +x gradlew
    
language: android
android:
 components:
    - build-tools-29.0.0
    - android-29
    - add-on
    - extra
    - platform-tools
    - tools
    - extra-google-googleplayservices
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-28
    - sys-img-armeabi-v7a-android-21
    
before_install:
 - yes | sdkmanager "platforms;android-29"