/*
 * Packager App backend API
 * Alábbiakban látható a Packager App-hoz használt adatbázis kezelő API leírása.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: tomi9994@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
